### ISSUE TITLE
'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by getcontrol** [chrise96/image-to-coco-json-converter#6]
Get this error when trying to convert these types of masks to json . I assume its because of the weird polygons:

[mask_sample](https://github.com/getcontrol/image-to-coco-json-converter/blob/master/dataset_crop/val_mask/bonirob_2016-05-23-10-37-10_0_frame41.png)

Similar issue reported here https://github.com/akTwelve/cocosynth/issues/9 and maybe fixed here https://github.com/akTwelve/cocosynth/blob/3909837290ab3511ff03ffe57ae870c929bd40a0/python/coco_json_utils.py

**Comment by chrise96** [comment]
Some objects in this image are indeed multipolygons because they include holes. Could you define the class ids that may be multipolygons in the "multipolygons_id" variable in the [main notebook](https://github.com/chrise96/image-to-coco-json-converter/blob/master/create-custom-coco-dataset.ipynb)? And set also the black background, the outlier, to a multipolygon.

**Comment by getcontrol** [comment]
I figured it out:
My masks weren't one uniform RGB color but instead a range of light grey & dark grey colors. I have it working on a dataset where masks RGB values are uniform

**Comment by alancarlosml** [comment]
Hi, I am getting the same error.

The error shows up in the following type of image:

![cju2mh8t6p07008350e01tx2a_0_3446](https://user-images.githubusercontent.com/413231/136619540-0686ee0f-279c-4153-ba38-d8e8faa7c448.jpg)

I've already tried to binarized it, but the error persists.

Could you please help me?

**Comment by enrj97** [comment]
Hi everyone!
Same error here for the following mask.

![48 20042200102788_15 615692138671875](https://user-images.githubusercontent.com/34503146/136917041-16d451e8-53ba-4e0b-821e-14e23aaad06a.png)



For me, the following code in `src.create_annotation.create_sub_mask_annotation` solves the problem:
```
if (poly.geom_type == 'MultiPolygon'):
            # if MultiPolygon, take the smallest convex Polygon containing all the points in the object
            poly = poly.convex_hull

if (poly.geom_type == 'Polygon'): # Ignore if still not a Polygon (could be a line or point)
            polygons.append(poly)
            segmentation = np.array(poly.exterior.coords).ravel().tolist()
            segmentations.append(segmentation)
```

**Comment by alancarlosml** [comment]
@enrj97 I've tried your code but I'm getting this error:

```
Traceback (most recent call last):
  File "/home/alan/mask2json/main.py", line 82, in <module>
    coco_format["images"], coco_format["annotations"], annotation_cnt = images_annotations_info(mask_path)
  File "/home/alan/mask2json/main.py", line 46, in images_annotations_info
    polygons, segmentations = create_sub_mask_annotation(sub_mask)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by enrj97** [comment]
@alancarlosml check this and try to cut off the small polygons.

https://github.com/akTwelve/cocosynth/blob/3909837290ab3511ff03ffe57ae870c929bd40a0/python/coco_json_utils.py

**Comment by sivamani-k** [comment]
> Hi everyone! Same error here for the following mask.
> 
> ![48 20042200102788_15 615692138671875](https://user-images.githubusercontent.com/34503146/136917041-16d451e8-53ba-4e0b-821e-14e23aaad06a.png)
> 
> For me, the following code in `src.create_annotation.create_sub_mask_annotation` solves the problem:
> 
> ```
> if (poly.geom_type == 'MultiPolygon'):
>             # if MultiPolygon, take the smallest convex Polygon containing all the points in the object
>             poly = poly.convex_hull
> 
> if (poly.geom_type == 'Polygon'): # Ignore if still not a Polygon (could be a line or point)
>             polygons.append(poly)
>             segmentation = np.array(poly.exterior.coords).ravel().tolist()
>             segmentations.append(segmentation)
> ```



> Hi everyone! Same error here for the following mask.
> 
> ![48 20042200102788_15 615692138671875](https://user-images.githubusercontent.com/34503146/136917041-16d451e8-53ba-4e0b-821e-14e23aaad06a.png)
> 
> For me, the following code in `src.create_annotation.create_sub_mask_annotation` solves the problem:
> 
> ```
> if (poly.geom_type == 'MultiPolygon'):
>             # if MultiPolygon, take the smallest convex Polygon containing all the points in the object
>             poly = poly.convex_hull
> 
> if (poly.geom_type == 'Polygon'): # Ignore if still not a Polygon (could be a line or point)
>             polygons.append(poly)
>             segmentation = np.array(poly.exterior.coords).ravel().tolist()
>             segmentations.append(segmentation)
> ```

This solution works in my case. Thank you so much for your solution.
