### ISSUE TITLE
I don't know this error

### ISSUE THREAD

**Issue by didnmj** [chrise96/image-to-coco-json-converter#7]
KeyError                                  Traceback (most recent call last)
[<ipython-input-4-41ea99310ecf>](https://localhost:8080/#) in <module>()
     84 
     85         # Create images and annotations sections
---> 86         coco_format["images"], coco_format["annotations"], annotation_cnt = images_annotations_info(mask_path)
     87 
     88         with open("output/{}.json".format(keyword),"w") as outfile:

[<ipython-input-4-41ea99310ecf>](https://localhost:8080/#) in images_annotations_info(maskpath)
     47         sub_masks = create_sub_masks(mask_image_open, w, h)
     48         for color, sub_mask in sub_masks.items():
---> 49             category_id = category_colors[color]
     50 
     51             # "annotations" info

KeyError: '(130, 130, 130)'

**Comment by apanand14** [comment]
Hey i'm getting the same error. Did you solve your problem??

Traceback (most recent call last):
  File "C:/image_to_coco_converter.py", line 89, in <module>
    coco_format["images"], coco_format["annotations"], annotation_cnt = images_annotations_info(mask_path)
  File "C:/image_to_coco_converter.py", line 50, in images_annotations_info
    category_id = category_colors[color]
KeyError: '(0, 255, 255)'

@chrise96 Your help will be appreciated. Thank you in advance!!

**Comment by apanand14** [comment]
hey, I got the error. Sorry for posting and tagging you!

**Comment by chrise96** [comment]
Hi @ikjoooon, 
You can define this RGB value in `category_colors` in the [main notebook](https://github.com/chrise96/image-to-coco-json-converter/blob/master/create-custom-coco-dataset.ipynb).
